#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

var="Best School"
var2="Hi"
i="1" 
while [ $i -lt 11 ];
do
	if [ $i -eq 10 ]; then
		echo "$var2"
	fi
      	echo "$var"
	((i++))
done

