#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

var1="Best School"
var2="bad luck"
var3="good luck"
i="1" 
while [ $i -lt 11 ];
do
	if [ $i -eq 4 ]; then
		echo "$var2"
	elif [ $i -eq 8 ]; then
		echo "$var3"
	else echo "$var1"

	fi
	((i++))
done

