#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes.
# It displays hours from 0 to 12 and minutes from 1 to 59.

i=0  # Hour counter
while [ $i -lt 13 ]; do
    echo "Hour: $i"
    
    s=1  # Minute counter
    while [ $s -lt 60 ]; do
        echo "$s"
        ((s++))
    done

    ((i++))
done

