#!/usr/bin/env bash
# Create PID file
echo $$ > /var/run/myscript.pid

# Function to clean up PID file and exit on SIGQUIT and SIGTERM
cleanup() {
    echo "Deleting PID file..."
    rm -f /var/run/myscript.pid
    exit 0
}

# Trap SIGTERM and SIGQUIT
trap 'echo "I hate the kill command"; cleanup' SIGTERM
trap 'cleanup' SIGQUIT

# Trap SIGINT
trap 'echo "Y U no love me?!"' SIGINT

# Display message indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done

